version: '3.8'
services:
  app1:
    build: .
    environment:
      - APP_NAME=app1
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
  
  app2:
    build: .
    environment:
      - APP_NAME=app2
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    command: npm start

  app3:
    build: .
    environment:
      - APP_NAME=app3
    ports:
      - "3002:3000"
    volumes:
      - .:/app
    command: npm start